name: Build python wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_wheels_cloud:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'pull_request' || github.repository == 'PalamaraLab/arg-needle-lib'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: auto64
            py-vers: cp38-* cp39-* cp310-* cp311-* cp312-*
            before-all: yum -y install boost-devel eigen3-devel hdf5-devel
            extra-env: ""
          - os: macos-13
            arch: x86_64
            py-vers: cp38-* cp39-* cp310-* cp311-* cp312-*
            before-all: brew install boost eigen hdf5
            extra-env: CC="$(brew --prefix llvm@15)/bin/clang" CXX="$(brew --prefix llvm@15)/bin/clang++" HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          - os: macos-14
            arch: arm64
            py-vers: cp39-* cp310-* cp311-* cp312-*
            before-all: brew install boost eigen hdf5
            extra-env: CC="$(brew --prefix llvm@15)/bin/clang" CXX="$(brew --prefix llvm@15)/bin/clang++" HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1

    env:
      CIBW_BUILD: ${{ matrix.py-vers }}
      CIBW_SKIP: cp3*-musllinux_*
      CIBW_ARCHS: ${{ matrix.arch }}
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
      CIBW_BEFORE_ALL: ${{ matrix.before-all }}
      CIBW_BEFORE_BUILD: pip install --upgrade pip setuptools wheel ninja numpy cython
      CIBW_ENVIRONMENT: ${{ matrix.extra-env }}
      MACOSX_DEPLOYMENT_TARGET: 10.15

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0

      - uses: actions/upload-artifact@v3
        with:
          name: wheels-cloud
          path: ./wheelhouse/*.whl
          retention-days: 1

  upload_all:
    name: Upload to PyPI
    needs: [build_wheels_cloud, build_wheels_self_hosted]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event.action == 'published' && github.repository == 'PalamaraLab/arg-needle-lib' }}

    steps:
      - uses: actions/setup-python@v3

      - name: Download wheels from cloud runners
        uses: actions/download-artifact@v3
        with:
          name: wheels-cloud
          path: wheels

      - name: Download wheels from self-hosted runner
        uses: actions/download-artifact@v3
        with:
          name: wheels-self-hosted
          path: wheels

      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: wheels/
